#!/usr/bin/env python3
"""Make FrontierSWE v2 tasks gradable by Harbor, without changing what is graded.

FrontierSWE v2 ships 34 Harbor-schema tasks but not the runner that uploads them
(``px-eval``), and the gap shows up only at scoring time. Every task errors with::

    Task environment directory <task>/tests has no environment definition

The agent phase is unaffected, so a run looks healthy and then yields no reward
at all. That is the worst failure mode a benchmark can have, and it is why the
first FrontierSWE grid produced provider metrics but no quality signal.

Why it fails
------------
Each task declares ``[verifier] environment_mode = "separate"``, so Harbor runs
the verifier in its own container built from ``<task>/tests`` as the build
context (``harbor/trial/trial.py:_verifier_env_build_context``). In separate mode
Harbor uploads **nothing** into that container (``skip_tests_upload=True``): the
image is expected to already carry ``/tests/test.sh``. That is the step px-eval
performs on upload, and the task.toml says so in a comment:

    # The verifier uses a fresh root-run container from the same content-pinned image.

But FrontierSWE keeps its graders at ``environment/tests/``, which its own
Dockerfile bakes to ``/root/tests/``, and ships no top-level ``tests/`` at all.
So the build context Harbor needs does not exist on disk.

What this does
--------------
For each task, materialize ``<task>/tests/`` as an exact copy of
``<task>/environment/`` plus two additions:

* ``harbor_test_entrypoint.sh``, a two-line shim that execs the real grader at
  ``/root/tests/test.sh``;
* two lines appended to the copied ``Dockerfile`` that install that shim at
  ``/tests/test.sh``.

The verifier image is therefore byte-identical to the agent image for every
layer except the final shim, which is what "the same content-pinned image"
means, and Docker's layer cache makes the second build nearly free.

What this deliberately does not do
----------------------------------
It does not touch ``environment/``, so the agent-side environment content hash is
unchanged and agent-phase results stay comparable with the ungraded first run. It
does not copy, rewrite, or even read the graders: ``verify.py``,
``compute_reward.py`` and the secret ``reference_bdcrc`` checksums travel inside
the image as root-owned files, exactly as upstream built them. The reward
therefore comes from upstream's scoring code, unmodified.

The pieces Harbor supplies at verification time are already what the graders
expect: the agent's ``artifacts`` (``source = "/app/"``) are re-materialized at
``/app/`` in the fresh verifier container, ``[verifier.env]`` is passed through,
the container runs as root, and ``/logs/verifier`` is bind-mounted back to the
host so ``reward.json`` and the evidence files land in the trial directory.

Usage
-----
::

    python3 scripts/fswe_prepare.py /path/to/frontier-swe-v2 \\
        --task crash-proof-flash-filesystem --task verilog-simulator-in-swift

    python3 scripts/fswe_prepare.py /path/to/frontier-swe-v2 --all-cpu-tasks

Idempotent: a ``tests/`` directory this script wrote is replaced, and one it did
not write is left alone and reported, so an upstream release that starts
shipping its own ``tests/`` is never silently overwritten.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

#: Written into the generated tests/ dir so a later run can tell its own output
#: from a tests/ directory that upstream started shipping.
STAMP_NAME = ".compound-generated"

STAMP_TEXT = """\
Generated by compound's scripts/fswe_prepare.py.

This directory is a copy of ../environment/ plus a verifier entrypoint shim, so
that Harbor can build the separate verifier container FrontierSWE v2's task.toml
asks for. Nothing here is hand-edited; delete it and re-run the script.
"""

SHIM_NAME = "harbor_test_entrypoint.sh"

SHIM_TEXT = """\
#!/bin/bash
# Harbor runs /tests/test.sh in the separate verifier container. The real grader
# is baked into the image at /root/tests/ by this task's own Dockerfile, so this
# shim only forwards to it: no scoring logic lives here.
exec /root/tests/test.sh
"""

DOCKERFILE_SUFFIX = """
# --- Harbor separate-verifier entrypoint (added by compound's fswe_prepare.py) ---
# In separate mode Harbor uploads no tests, so /tests/test.sh must exist in the
# image. It forwards to the task's own grader at /root/tests/test.sh.
COPY {shim} /tests/test.sh
RUN chmod 0755 /tests/test.sh
"""


def prepare_task(task_dir: Path, *, force: bool = False) -> str:
    """Materialize ``task_dir/tests``. Returns a one-line status for reporting."""
    name = task_dir.name
    environment = task_dir / "environment"
    dockerfile = environment / "Dockerfile"
    grader = environment / "tests" / "test.sh"
    tests = task_dir / "tests"

    if not dockerfile.is_file():
        return f"SKIP {name}: no environment/Dockerfile"
    if not grader.is_file():
        return f"SKIP {name}: no environment/tests/test.sh to forward to"
    if tests.exists() and not (tests / STAMP_NAME).is_file() and not force:
        return f"SKIP {name}: tests/ exists and was not generated by this script"

    if tests.exists():
        shutil.rmtree(tests)
    # copy2 preserves the exec bits the setup scripts rely on.
    shutil.copytree(environment, tests, symlinks=True)

    (tests / SHIM_NAME).write_text(SHIM_TEXT)
    (tests / SHIM_NAME).chmod(0o755)
    (tests / STAMP_NAME).write_text(STAMP_TEXT)
    with (tests / "Dockerfile").open("a") as handle:
        handle.write(DOCKERFILE_SUFFIX.format(shim=SHIM_NAME))
    return f"ok   {name}"


def cpu_only_tasks(tasks_dir: Path, *, max_memory_mb: int) -> list[str]:
    """Task names that need no GPU and fit ``max_memory_mb``, cheapest first.

    Reads the declared requirements rather than guessing: 11 of the 34 tasks ask
    for at least one GPU, and two ask for 128 GB of RAM, so a grid that fans out
    one VM per provider arm can only afford the low end of the range.
    """
    # Imported here, not at module scope: tomllib is 3.11+, and this script has
    # to run under whatever python3 a fresh Ubuntu 22.04 VM ships (3.10). Only
    # --all-cpu-tasks needs to read task.toml; --task never does.
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - exercised on 3.10 VMs
        import tomli as tomllib  # type: ignore[no-redef]

    picked: list[tuple[int, int, str]] = []
    for toml_path in sorted(tasks_dir.glob("*/task.toml")):
        config = tomllib.loads(toml_path.read_text())
        env = config.get("environment", {})
        verifier_env = config.get("verifier", {}).get("environment", {})
        gpus = max(env.get("gpus", 0) or 0, verifier_env.get("gpus", 0) or 0)
        memory = max(env.get("memory_mb", 0) or 0, verifier_env.get("memory_mb", 0) or 0)
        cpus = max(env.get("cpus", 0) or 0, verifier_env.get("cpus", 0) or 0)
        if gpus or memory > max_memory_mb:
            continue
        picked.append((memory, cpus, toml_path.parent.name))
    return [name for _, _, name in sorted(picked)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("repo", type=Path, help="a frontier-swe-v2 checkout")
    parser.add_argument("--task", action="append", default=[], help="task name, repeatable")
    parser.add_argument(
        "--all-cpu-tasks",
        action="store_true",
        help="every task needing no GPU and at most --max-memory-mb of RAM",
    )
    parser.add_argument("--max-memory-mb", type=int, default=8192)
    parser.add_argument(
        "--force", action="store_true", help="overwrite a tests/ this script did not write"
    )
    parser.add_argument("--list", action="store_true", help="print the selection and exit")
    args = parser.parse_args()

    tasks_dir = args.repo / "tasks"
    if not tasks_dir.is_dir():
        print(f"error: {tasks_dir} is not a directory; pass a frontier-swe-v2 checkout")
        return 1

    names = list(args.task)
    if args.all_cpu_tasks:
        names += [n for n in cpu_only_tasks(tasks_dir, max_memory_mb=args.max_memory_mb)
                  if n not in names]
    if not names:
        parser.error("pass --task NAME (repeatable) or --all-cpu-tasks")

    if args.list:
        for name in names:
            print(name)
        return 0

    failures = 0
    for name in names:
        task_dir = tasks_dir / name
        if not task_dir.is_dir():
            print(f"SKIP {name}: no such task")
            failures += 1
            continue
        line = prepare_task(task_dir, force=args.force)
        print(line)
        failures += line.startswith("SKIP")
    print(f"\n{len(names) - failures} of {len(names)} tasks prepared.")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
